overc-installer: fix the issue of missing chvt.service
Installer didn't copy the chvt.service into the installer
image, and thus will cause the following error:

ERROR: Could not locate service chvt.service ## ERROR

when run the cubeit-installer to deploy the overc system
to a local hd drive.

Signed-off-by: fupan.li <lifupan@gmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>